<div class="Mail_subscription">
	<form method="post" action="http://www.milanoo.com/mail/subscribe.html">
	<input type="text" onblur="if (this.value == '') this.value = 'Your Email Address';" onfocus="if (this.value == 'Your Email Address') this.value = '';" value="Your Email Address" class="login_input" name="email" gtbfieldid="2">
	<input type="submit" value="Subscribe" name="Submit5" class="button_01">
	</form>
</div>