<div class="left_box">
    	<div class="Categories_name">
	<h2 class="dark font_size12">
	Wedding Dresses	</h2>
	<ul id="Caracoter_lb">
      <li>
                   	<span class="red fontbold">Wedding Dresses Under $100</span>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-Reception-Dresses-c1616">
        		Reception Dresses        	</a>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-Beach-Wedding-Dresses-c1427">
        		Beach Wedding Dresses        	</a>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-Wedding-Dresses-2011-Collection-c825">
        		Wedding Dresses 2011 Collection        	</a>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-Luxury-Wedding-Dresses-c1060">
        		Luxury Wedding Dresses        	</a>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-Mini-Wedding-Dresses-c1061">
        		Mini Wedding Dresses        	</a>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-A-line-Wedding-Dresses-c810">
        		A-line Wedding Dresses        	</a>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-Ball-Gown-Wedding-Dresses-c811">
        		Ball Gown Wedding Dresses        	</a>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-V-neck-Wedding-Dresses-c816">
        		V-neck Wedding Dresses        	</a>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-Trumpet-Mermaid-Wedding-Dresses-c812">
        		Trumpet/Mermaid Wedding Dresses        	</a>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-Sheath-Column-Wedding-Dresses-c831">
        		Sheath/Column Wedding Dresses        	</a>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-Empire-Waist-Wedding-Dresses-c813">
        		Empire Waist Wedding Dresses        	</a>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-Halter-Wedding-Dresses-c818">
        		Halter Wedding Dresses        	</a>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-Off-the-shoulder-Wedding-Dresses-c814">
        		Off-the-shoulder Wedding Dresses        	</a>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-Strapless-Wedding-Dresses-c815">
        		Strapless Wedding Dresses        	</a>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-Sweetheart-Wedding-Dresses-c817">
        		Sweetheart Wedding Dresses        	</a>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-Maternity-Wedding-Dresses-c746">
        		Maternity Wedding Dresses        	</a>
                 </li>
      
      <li>
                   	<a href="http://www.milanoo.com/wholesale-Plus-Size-Wedding-Dresses-c809">
        		Plus Size Wedding Dresses        	</a>
                 </li>
      
	</ul>
    
    <script>
	var tmpContent = jq('&lt;div&gt;&lt;/div&gt;').append(jq("#Caracoter_lb").clone()).html();	
    </script>	   	
</div>   <div class="hei10"></div>
   <div id="selectors" class="selector_class">
     <div><a class="float_right Light_gray2" id="left_cont_allclear" href="javascript:void(0)">All Clear</a><span class="Orange fontbold font_size14">REFINE BY</span></div>
     <div class="hei5"></div>
     <div class="Selector_title">PRICE RANGE</div>
		 <div class="Ruler_selector ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" id="Ruler_selector"><div class="ui-slider-range ui-widget-header" style="left: 0%; width: 100%;"></div><a href="#" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 0%;"><div class="selector_content">US$42</div></a><a href="#" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 100%;"><div class="selector_content">US$164</div></a></div>
     <!--<div class="Ruler_selector">
       <div class="Fixed_size"></div>
       <div class="Flexible_size">
         <div class="selector_content">$10000</div>
       </div>
     </div>-->
     <div class="font_size11 Light_gray2 height20">
	 <div class="float_left">US$42</div>
	 <div class="float_right">US$164</div>
	 </div>
     <div class="line2"></div>
     <div class="hei10"></div>
             	     	<div aidname="321" class="Selector_title">Length</div>
	     	<div class="Brand_selector noborder ">
        		<ul>
	     				     	<li><input type="checkbox" autocomplete="off" value="length1" id="itemCKBtea length "><label for="itemCKBtea length ">tea length </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="length2" id="itemCKBfloor length "><label for="itemCKBfloor length ">floor length </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="length3" id="itemCKBknee length "><label for="itemCKBknee length ">knee length </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="length4" id="itemCKBsweep "><label for="itemCKBsweep ">sweep </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="length5" id="itemCKBmini "><label for="itemCKBmini ">mini </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="length6" id="itemCKBshort "><label for="itemCKBshort ">short </label></li>
		     		     		     	</ul>
	     </div>
	     <div class="line2"></div>
     <div class="hei10"></div>
             	     	<div aidname="322" class="Selector_title">Neckline</div>
	     	<div class="Brand_selector  Brand_selector_over">
        		<ul>
	     				     	<li><input type="checkbox" autocomplete="off" value="neckline1" id="itemCKBsweetheart "><label for="itemCKBsweetheart ">sweetheart </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="neckline2" id="itemCKBv-neck "><label for="itemCKBv-neck ">v-neck </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="neckline3" id="itemCKBoff-the-shoulder "><label for="itemCKBoff-the-shoulder ">off-the-shoulder </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="neckline4" id="itemCKBone-shoulder "><label for="itemCKBone-shoulder ">one-shoulder </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="neckline5" id="itemCKBhalter "><label for="itemCKBhalter ">halter </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="neckline6" id="itemCKBstrapless "><label for="itemCKBstrapless ">strapless </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="neckline7" id="itemCKBspaghetti "><label for="itemCKBspaghetti ">spaghetti </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="neckline8" id="itemCKBsquare "><label for="itemCKBsquare ">square </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="neckline9" id="itemCKBscoop "><label for="itemCKBscoop ">scoop </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="neckline10" id="itemCKBjewel "><label for="itemCKBjewel ">jewel </label></li>
		     		     		     	</ul>
	     </div>
	     <div class="line2"></div>
     <div class="hei10"></div>
             	     	<div aidname="323" class="Selector_title">Silhouette</div>
	     	<div class="Brand_selector  Brand_selector_over">
        		<ul>
	     				     	<li><input type="checkbox" autocomplete="off" value="silhouette1" id="itemCKBa-line "><label for="itemCKBa-line ">a-line </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="silhouette2" id="itemCKBball gown "><label for="itemCKBball gown ">ball gown </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="silhouette3" id="itemCKBmermaid trumpet "><label for="itemCKBmermaid trumpet ">mermaid trumpet </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="silhouette4" id="itemCKBempire waist "><label for="itemCKBempire waist ">empire waist </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="silhouette5" id="itemCKBmaternity "><label for="itemCKBmaternity ">maternity </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="silhouette6" id="itemCKBplus size "><label for="itemCKBplus size ">plus size </label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="silhouette7" id="itemCKBsheath "><label for="itemCKBsheath ">sheath </label></li>
		     		     		     	</ul>
	     </div>
	     <div class="line2"></div>
     <div class="hei10"></div>
             	     	<div aidname="320" class="Selector_title">Fabric</div>
	     	<div class="Brand_selector  Brand_selector_over">
        		<ul>
	     				     	<li><input type="checkbox" autocomplete="off" value="fabric1" id="itemCKBsatin"><label for="itemCKBsatin">satin</label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="fabric2" id="itemCKBtaffeta"><label for="itemCKBtaffeta">taffeta</label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="fabric3" id="itemCKBchiffon"><label for="itemCKBchiffon">chiffon</label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="fabric4" id="itemCKBlace"><label for="itemCKBlace">lace</label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="fabric5" id="itemCKBsilk"><label for="itemCKBsilk">silk</label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="fabric6" id="itemCKBorganza"><label for="itemCKBorganza">organza</label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="fabric7" id="itemCKBtulle"><label for="itemCKBtulle">tulle</label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="fabric8" id="itemCKBnet"><label for="itemCKBnet">net</label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="fabric9" id="itemCKBmatte satin"><label for="itemCKBmatte satin">matte satin</label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="fabric10" id="itemCKBelastic woven satin"><label for="itemCKBelastic woven satin">elastic woven satin</label></li>
		     			     	<li><input type="checkbox" autocomplete="off" value="fabric11" id="itemCKBsilk like satin"><label for="itemCKBsilk like satin">silk like satin</label></li>
		     		     		     	</ul>
	     </div>
	     <div class="line2"></div>
     <div class="hei10"></div>
               <div aidname="bid" class="Selector_title">Brand</div>
     <div class="Brand_selector noborder">
        <ul>
                  <li><input type="checkbox" autocomplete="off" value="2" id="bandCKB2" name=""><label for="bandCKB2">Miama</label></li>
                </ul>
     </div>
     <div class="line2"></div>
     <div class="hei5"></div>
          <div class="font_size11 talign_center">
     <a href="javascript:" onclick="alterSearch({'class':'1615','p_num':'24','viewtype':'thing_grid.htm','textfield':'','fieldname':'','order':'desc','tab':'','category':'','prices':'','pricee':''},this)" class="dark fontbold" rel="nofollow" id="searchMethodLink_1">all</a>
      | <a href="javascript:" onclick="alterSearch({'class':'1615','p_num':'24','viewtype':'thing_grid.htm','textfield':'','fieldname':'','order':'desc','tab':'Promotions','category':'area99','prices':'','pricee':''},this)" class="Light_gray2" rel="nofollow" id="searchMethodLink_2">Special Offers</a>  | <a onclick="alterSearch({'class':'1615','p_num':'24','viewtype':'thing_grid.htm','textfield':'','fieldname':'','order':'desc','tab':'Promotions','category':'PFreeShipping','prices':'','pricee':''},this)" href="javascript:" class="Light_gray2" rel="nofollow" id="searchMethodLink_3">FreeShipping</a></div>
     <div class="hei10"></div>
   <div style="width: 191px; height: 859px; background: none repeat scroll 0% 0% rgb(233, 233, 233); opacity: 0.2; position: absolute; z-index: 999; top: 0px; left: 0px; display: none;"></div></div>
   <div class="hei10"></div>
      <div class="top5selling">
     <h3 class="red font_size16">TOP SELLING</h3>
     <ul>
          </ul>
    <div class="hei1"></div>
</div>   <div class="hei10"></div>
         <div class="Mail_subscription">
	<form method="post" action="http://www.milanoo.com/mail/subscribe.html">
	<input type="text" onblur="if (this.value == '') this.value = 'Your Email Address';" onfocus="if (this.value == 'Your Email Address') this.value = '';" value="Your Email Address" class="login_input" name="email">
	<input type="submit" value="Subscribe" name="Submit5" class="button_01">
	</form>
</div>  </div>