package com.spshop.model;

public class Country extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = 168229983824448541L;
	
	private String code;
	private String abbrCode;
	private Image icon;
	
	public Country() {
		// TODO Auto-generated constructor stub
	}
	
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getAbbrCode() {
		return abbrCode;
	}
	public void setAbbrCode(String abbrCode) {
		this.abbrCode = abbrCode;
	}
	public Image getIcon() {
		return icon;
	}
	public void setIcon(Image icon) {
		this.icon = icon;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public Country clone() {
		Country obj = null;
		obj = new Country();
		if (this.code != null) {
			/* Does not have a clone() method */
			obj.code = this.code;
		}
		if (this.abbrCode != null) {
			/* Does not have a clone() method */
			obj.abbrCode = this.abbrCode;
		}
		if (this.icon != null) {
			obj.icon = (Image) this.icon.clone();
		}
		return obj;
	}
}
