package com.spshop.model;

public class Coupon extends Promotion{

	/**
	 * 
	 */
	private static final long serialVersionUID = -7687544509171356012L;

	private String code;
	private float value;
	
	public Coupon() {
		// TODO Auto-generated constructor stub
	}
	
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public float getValue() {
		return value;
	}
	public void setValue(float value) {
		this.value = value;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public Coupon clone() {
		Coupon obj = null;
		obj = new Coupon();
		if (this.code != null) {
			/* Does not have a clone() method */
			obj.code = this.code;
		}
		obj.value = this.value;
		return obj;
	}

}
