package com.spshop.model;

public class Deliver extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = -817593465733096672L;
	
	private String company;
	private Image icon;
	private float price;
	
	public Deliver() {
		// TODO Auto-generated constructor stub
	}
	
	public String getCompany() {
		return company;
	}
	public void setCompany(String company) {
		this.company = company;
	}
	public Image getIcon() {
		return icon;
	}
	public void setIcon(Image icon) {
		this.icon = icon;
	}
	public float getPrice() {
		return price;
	}
	public void setPrice(float price) {
		this.price = price;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public Deliver clone() {
		Deliver obj = null;
		obj = new Deliver();
		if (this.company != null) {
			/* Does not have a clone() method */
			obj.company = this.company;
		}
		if (this.icon != null) {
			obj.icon = (Image) this.icon.clone();
		}
		obj.price = this.price;
		return obj;
	}
}
