package com.spshop.model;

import java.util.List;


public class OrderItem extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = -6303793659582817131L;

	private Order order;
	private Product product;
	private int quantity;
	private float finalPrice;
	private List<UserOption> userOptions; 
	
	public OrderItem() {
		// TODO Auto-generated constructor stub
	}
	
	public Order getOrder() {
		return order;
	}
	public void setOrder(Order order) {
		this.order = order;
	}
	public Product getProduct() {
		return product;
	}
	public void setProduct(Product product) {
		this.product = product;
	}
	public int getQuantity() {
		return quantity;
	}
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	public float getFinalPrice() {
		return finalPrice;
	}
	public void setFinalPrice(float finalPrice) {
		this.finalPrice = finalPrice;
	}
	public void setUserOptions(List<UserOption> userOptions) {
		this.userOptions = userOptions;
	}
	public List<UserOption> getUserOptions() {
		return userOptions;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public OrderItem clone() {
		OrderItem obj = null;
		obj = new OrderItem();
		if (this.order != null) {
			obj.order = (Order) this.order.clone();
		}
		if (this.product != null) {
			obj.product = (Product) this.product.clone();
		}
		obj.quantity = this.quantity;
		obj.finalPrice = this.finalPrice;
		if (this.userOptions != null) {
			/* Does not have a clone() method */
			obj.userOptions = this.userOptions;
		}
		return obj;
	}
	
}
