package com.spshop.model;

public class OrderStatus extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = 3100319255187191566L;
	
	private String status;
	
	public OrderStatus() {
		// TODO Auto-generated constructor stub
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatus() {
		return status;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public OrderStatus clone() {
		OrderStatus obj = null;
		obj = new OrderStatus();
		if (this.status != null) {
			/* Does not have a clone() method */
			obj.status = this.status;
		}
		return obj;
	}


}
