package com.spshop.model;

public class Site extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = 8581772837790501820L;
	
	private Image logo;
	private String prefix;
	private String suffix;
	private String domain;
	private String imagePath;
	private String imageMagicCommand;
	private String siteFooter;
	private String sideBar;
	
	public Site() {
	}
	
	public Site(Site site) {
		super(site);
	}

	public Image getLogo() {
		return logo;
	}

	public void setLogo(Image logo) {
		this.logo = logo;
	}

	public String getPrefix() {
		return prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	public String getSuffix() {
		return suffix;
	}

	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	public String getImagePath() {
		return imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	public void setImageMagicCommand(String imageMagicCommand) {
		this.imageMagicCommand = imageMagicCommand;
	}

	public String getImageMagicCommand() {
		return imageMagicCommand;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getDomain() {
		return domain;
	}
	
	public String getHost(){
		return prefix+"."+domain+"."+suffix;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public Site clone() {
		Site obj = null;
		obj = new Site(this);
		if (this.logo != null) {
			obj.logo = (Image) this.logo.clone();
		}
		if (this.prefix != null) {
			/* Does not have a clone() method */
			obj.prefix = this.prefix;
		}
		if (this.suffix != null) {
			/* Does not have a clone() method */
			obj.suffix = this.suffix;
		}
		if (this.domain != null) {
			/* Does not have a clone() method */
			obj.domain = this.domain;
		}
		if (this.imagePath != null) {
			/* Does not have a clone() method */
			obj.imagePath = this.imagePath;
		}
		
		if (this.siteFooter != null) {
			/* Does not have a clone() method */
			obj.siteFooter = this.siteFooter;
		}
		if (this.sideBar != null) {
			/* Does not have a clone() method */
			obj.sideBar = this.sideBar;
		}
		
		if (this.imageMagicCommand != null) {
			/* Does not have a clone() method */
			obj.imageMagicCommand = this.imageMagicCommand;
		}
		return obj;
	}

	public void setSiteFooter(String siteFooter) {
		this.siteFooter = siteFooter;
	}

	public String getSiteFooter() {
		return siteFooter;
	}

	public void setSideBar(String sideBar) {
		this.sideBar = sideBar;
	}

	public String getSideBar() {
		return sideBar;
	}

}
