package com.spshop.model;

import com.spshop.model.enums.SelectType;

public class UserOption extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1976590524674580292L;
	
	private String optionName;
	private String value;
	private String strOptionType;
	//private OrderItem orderItem;
	
	public UserOption() {
		// TODO Auto-generated constructor stub
	}
	
	public UserOption(UserOption option) {
		super(option);
	}
	
	public String getOptional() {
		return optionName;
	}
	public void setOptional(String optional) {
		this.optionName = optional;
	}
	public String getValue() {
		return value;
	}
	public void setValue(String value) {
		this.value = value;
	}

	public String getOptionName() {
		return optionName;
	}

	public void setOptionName(String optionName) {
		this.optionName = optionName;
	}

	public String getStrOptionType() {
		return strOptionType;
	}

	public void setStrOptionType(String strOptionType) {
		this.strOptionType = strOptionType;
	}

	public void setOptionType(SelectType selectType) {
		this.strOptionType = selectType.getValue();
	}
	
	public SelectType getOptionType() {
		return SelectType.valueOf(strOptionType);
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public UserOption clone() {
		UserOption obj = null;
		obj = new UserOption(this);
		if (this.optionName != null) {
			/* Does not have a clone() method */
			obj.optionName = this.optionName;
		}
		if (this.value != null) {
			/* Does not have a clone() method */
			obj.value = this.value;
		}
		if (this.strOptionType != null) {
			/* Does not have a clone() method */
			obj.strOptionType = this.strOptionType;
		}
		return obj;
	}
	
	
	
}
