package com.spshop.model;

public class UserOption extends Component{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1976590524674580292L;
	
	private String optional;
	private String value;
	private OrderItem orderItem;
	
	public UserOption() {
		// TODO Auto-generated constructor stub
	}
	
	public String getOptional() {
		return optional;
	}
	public void setOptional(String optional) {
		this.optional = optional;
	}
	public String getValue() {
		return value;
	}
	public void setValue(String value) {
		this.value = value;
	}
	public OrderItem getOrderItem() {
		return orderItem;
	}
	public void setOrderItem(OrderItem orderItem) {
		this.orderItem = orderItem;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * clone
	 * @return Object
	 */
	public UserOption clone() {
		UserOption obj = null;
		obj = new UserOption();
		if (this.optional != null) {
			/* Does not have a clone() method */
			obj.optional = this.optional;
		}
		if (this.value != null) {
			/* Does not have a clone() method */
			obj.value = this.value;
		}
		if (this.orderItem != null) {
			obj.orderItem = (OrderItem) this.orderItem.clone();
		}
		return obj;
	}
	
}
